site_title = "MyArxiv"
limit_days = 7
cache_url = "https://xenvocus.github.io/AstroArxiv/cache.json"

[[sources]]
limit = 150
category = "astro-ph.HE"
title = "High Energy Astrophysical Phenomena"

[[sources]]
limit = 150
category = "astro-ph.IM"
title = "Instrumentation and Methods for Astrophysics"

[[sources]]
limit = 150
category = "astro-ph.CO"
title = "Cosmology and Nongalactic Astrophysics"

[[sources]]
limit = 150
category = "astro-ph.EP"
title = "Earth and Planetary Astrophysics"

[[sources]]
limit = 150
category = "astro-ph.GA"
title = "Astrophysics of Galaxies"

[[sources]]
limit = 150
category = "astro-ph.SR"
title = "Solar and Stellar Astrophysics"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"






